### ISSUE TITLE
Curious Back & Forward Animation Behavior

### ISSUE THREAD

**Issue by nyquist212** [kamisama/cal-heatmap#113]
When user 'accidentally' double-clicks the forward and backwards animation controls, redrawing seems to get messed up (sorry, that's about as technical I can describe it). If user consistently double-clicks controls as they navigate forwards and backwards, very strange behaviors begin to be experienced. 
Hosted example here:
http://colinwhite.net/AtxUtilization/
Code here:
https://github.com/nyquist212/AtxUtilization
I wouldn't be surprised if it's just my implementation. 
Is there a solution or workaround I can use to mitigate this?

**Comment by kamisama** [comment]
See #134
