### ISSUE TITLE
There is an issue with the custom scale ranges

### ISSUE THREAD

**Issue by suresh44t** [kamisama/cal-heatmap#116]
There is an issue with the custom scale ranges, though we give a different scale range it is always taking as 10-40

In this example http://jsfiddle.net/Kamisama/4aDdJ/1/ , the scale range in the JS code is 40-100, but when you hover it on the actual labels its range is 10-40.

**Comment by kamisama** [comment]
`scale` is not a valid option for the v3 version. Use `legend` instead
