### ISSUE TITLE
AMD Error

### ISSUE THREAD

**Issue by infacq** [kamisama/cal-heatmap#129]
`Uncaught Error: Module name "d3" has not been loaded yet for context: _. Use require([])`

does anyone experience this?

here is my setup 

````
define(function (require) {
    "use strict";
	
    var       calheatcss      = require("css!style/cal-heatmap"),
		d3                   = require("d3"),
		CalHeatMap    = require("cal-heatmap");

});

**Comment by kamisama** [comment]
A fix with #124 should be on the way

**Comment by infacq** [comment]
looking forward https://github.com/kamisama/cal-heatmap/pull/124

**Comment by infacq** [comment]
this issue still has the issue. Could you fix for AMD

**Comment by yangpu** [comment]
This issue is there when concat it into bundle file by r.js optimizer.
