### ISSUE TITLE
Days With Data Showing Up As If Empty

### ISSUE THREAD

**Issue by Linell** [kamisama/cal-heatmap#130]
I've got the following chart configuration:

```coffeescript
    vm.heatmapConfig =
      domain: 'month'
      start: new Date(Object.keys(vm.data)[0] * 1000)
      end: new Date(Object.keys(vm.data)[Object.keys(vm.data).length - 1] * 1000)
      subDomain: 'day'
      domainGutter: 1
      range: 11
      cellSize: 15
      data: vm.data
```

This is being set in angular via the [angular-cal-heatmap-directive](https://github.com/shekhargulati/angular-cal-heatmap-directive/blob/master/app/scripts/calHeatmap.js). Looking at the directive's code, I don't think that the problem would be in it as it's very simple.

By doing `$('#ada-heatmap').calHeatmap()` I got this:
![screen shot 2015-01-23 at 3 38 47 pm](https://cloud.githubusercontent.com/assets/1231554/5883353/176cee38-a317-11e4-965e-b977baed206d.png)

You can see that the 30th of October (the 29 object above) does not display as if it has any data. In fact, the majority of the seemingly empty days actually have data!
![screen shot 2015-01-23 at 3 38 38 pm](https://cloud.githubusercontent.com/assets/1231554/5883360/2e281ab2-a317-11e4-82c8-88440aebc812.png)

Even stranger, though, is the fact that hovering over it displays the correct data
![screen shot 2015-01-23 at 3 48 22 pm](https://cloud.githubusercontent.com/assets/1231554/5883380/50164b62-a317-11e4-91c5-decaa1df36bc.png)

**Comment by Linell** [comment]
I've noticed that every item that should be colored and is not has a value greater than 10. The legend's darkest value is "More than 10 items"

**Comment by kamisama** [comment]
Is the issue occuring for the whole calendar, or just for dates after a certain date ? Is that certain the day of DST ?

**Comment by kamisama** [comment]
Can you tell me what classes are applied to the cells with the issue ?

**Comment by Linell** [comment]
I actually found that the problem was being caused by items with a value greater than ten. Despite the legend's indication that anything greater than ten would be the darkest color, none of the items had color. Setting the 

```coffeescript
      legend: [0, 10, 20, 30, 40, 50, 60]
```

colors all of the items that need to be colored.

It's still odd that they weren't colored at all. I can remove those changes and give you the classes if you'd like. Also, it was for all of the calendar, not just certain dates.

**Comment by kamisama** [comment]
Yes please. Knowing what classes are applied to the cells is the first step for debugging. I want to know if it's a problem related to the stylesheets, or the classes themselves are missing.

Could you also provide a sample of your data ?

**Comment by Linell** [comment]
This one is not colored and should be:

![screen shot 2015-01-26 at 8 36 24 am](https://cloud.githubusercontent.com/assets/1231554/5901243/78b1bdc4-a536-11e4-82a2-5bd44ada7dad.png)

This one is colored correctly:

![screen shot 2015-01-26 at 8 37 18 am](https://cloud.githubusercontent.com/assets/1231554/5901255/943e1ef2-a536-11e4-9d0d-0dc54460b238.png)

---

Here is a sample of the data

```json
{
  "1375678800": 0,
  "1375765200": 1,
  "1375851600": 4,
  "1375938000": 2,
  "1376024400": 1,
  "1376283600": 36,
  "1376370000": 34,
  "1376456400": 45,
  "1376542800": 39,
  "1376629200": 36,
  "1376888400": 81,
  "1376974800": 35,
  "1377061200": 43,
  "1377147600": 52
}
```

**Comment by kamisama** [comment]
Do you have the `q6` class in your css ?

**Comment by Linell** [comment]
I do not. I'm using the [cal-heatmap.css](https://github.com/kamisama/cal-heatmap/blob/master/cal-heatmap.css#L58-L86) and haven't modified it at all. I also haven't overridden `q6` anywhere else.

**Comment by kamisama** [comment]
I thinks that's the issue. You have to add the additional `qn` classes in your css when your legend have more than 5 colors.

**Comment by Linell** [comment]
Ah, I see. I expected it to take my data and automagically segment it into 5 bands and color based off of that. 

I've now got my code set up to do that for me and set legend to that array and it works fine. Thank you for your help!

**Comment by kamisama** [comment]
Use the `legendColor` option if you want magic coloring, instead of css.
