### ISSUE TITLE
Select multiple subdomains 

### ISSUE THREAD

**Issue by JoabMendes** [kamisama/cal-heatmap#135]
I would like to build a time range selector using the chart. (Select a range of days)
So, is it possible to make multiple selection of subdomains using the mouse?
If it's, how can I do that?

**Comment by kamisama** [comment]
Not possible yet. This is not the main purpose of this tool.

How will you use it ?

**Comment by JoabMendes** [comment]
I found another way to select the range using the chart. Isn't sophisticated as I was expecting but solved the problem. The user can click in two subdomains and I highlight the other subdomains within these two clicked subdomains. It's not dragging as I wished, but works. :+1:
