### ISSUE TITLE
Missing Directories in 3.5.2

### ISSUE THREAD

**Issue by erolg** [kamisama/cal-heatmap#136]
The last release (3.5.2) there is no such a file or directories which is named node_modules
```<script src="../node_modules/qunitjs/qunit/qunit.js"></script>```
```<script src="../node_modules/jquery/jquery.min.js"></script>```
So test/index.html shows nothing.

**Comment by kamisama** [comment]
You have to run `npm install` in order to install all the dependencies needed for the tests

**Comment by erolg** [comment]
Thanks :)
