### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Cyr69** [kamisama/cal-heatmap#141]
What that is possible to translate months and text into French ?

**Comment by kamisama** [comment]
Use the moment.js library to format the dates

**Comment by Cyr69** [comment]
How can I use it?

**Comment by kamisama** [comment]
Take a look at http://kamisama.github.io/cal-heatmap/#subDomainDateFormat

**Comment by Cyr69** [comment]
Nice job ! Thank you :)
