### ISSUE TITLE
Color custom by value

### ISSUE THREAD

**Issue by Cyr69** [kamisama/cal-heatmap#142]
Hello,

What that is possible to define personalized colors and to attribute him according to the associated values?
At present, we can make only of the gradation.

Example :
var my_data = {
        "1338847200":10
        ,"1338933600":20
        ,"1339020000":20
        ,"1339106400":20
        ,"1339192800":20
        ,"1339279200":30
        ,"1339365600":30
        ,"1339452000":30
        ,"1339538400":50
        ,"1339624800":50
        ,"1339711200":50
        ,"1339797600":50
        ,"1339884000":50
        ,"1339970400":50
        ,"1340056800":40
        ,"1340143200":40
        ,"1340229600":40
        ,"1340316000":40
        ,"1340402400":40
        ,"1340488800":40
        ,"1340575200":40
    };

Color :
10 = red
20 = blue
30 = green
40 = grey
50 = yellow

What that is possible to make it with your plugin?

Thanks in advance.

Best regards.

**Comment by kamisama** [comment]
Yes

Define a legend for each of your colors with the `legend` option: http://kamisama.github.io/cal-heatmap/#legend

Example: 
```javascript
legend: [15, 25, 35, 45]
```

This will create a legend with 5 differents colors for each of you values: 

* .q1 : < 15
* .q2 : between 15 and 25
* .q3 : between 25 and 35
* .q4 : between 35 and 45
* .q5 : > 45

Now, open the CSS file, and create these classes

```css
.q1 { fill: red }
// etc ...
```

**Comment by Cyr69** [comment]
It okay ! Thank you !
