### ISSUE TITLE
How to interact with a calendar several times

### ISSUE THREAD

**Issue by borjita1** [kamisama/cal-heatmap#149]
Hi,

First of all, this heatmap is awesome!!! Congratulations to who built it!

My problem is that I don't know how to interact with a calendar several times.

When I first load the site, I create an empty calendar like this, which works perfectly:

var cal = new CalHeatMap();
   cal.init({
   itemNamespace: "cal",
    domain: "month",
	/*afterLoadData: parser,*/
    start: new Date(2012, 0),
	cellSize: 15,
	cellPadding: 5,
	domainGutter: 5,
    /*subDomainTextFormat: function(date ,value) {
		return value;
	},*/
	range: 12,
   legendColors: {
		empty: "#ededed",
		min: "#40ffd8",
		max: "#f20013"
	},
    itemName: ["request", "requests"],
    legend: [2, 3, 4, 5, 6],
    /*domainLabelFormat: "%m-%y"*/
  
});

Then, when I press a button, it calls a javascript function that loads the data, and ideally should change the first calendar that I created, but instead is creating a new calendar under the first one.

function reloadcalendar(){

  cal.init({
    itemNamespace: "cal",
    domain: "month",
	data: jsonfinal,
	/*afterLoadData: parser,*/
    start: new Date(2012, 0),
	cellSize: 15,
	cellPadding: 5,
	domainGutter: 5,
    /*subDomainTextFormat: function(date ,value) {
		return value;
	},*/
	range: 12,
   legendColors: {
		empty: "#ededed",
		min: "#40ffd8",
		max: "#f20013"
	},
 
    itemName: ["request", "requests"],
    legend: [2, 3, 4, 5,6],
    /*domainLabelFormat: "%m-%y"*/
  
});
}

What am I doing wrong?? :( I have tried anything, and I don't know how to make this work!!

Also, another smaller doubt, is it possible that the calendar detect automatically the limits of the legend according to the min and max value of the json, so I don't have to manually change legend: [2, 3, 4, 5,6] all the time?

Thanks!

**Comment by kamisama** [comment]
The answer is on the first line of your example:

    var cal = new CalHeatMap();

`cal` is the variable, enabling you to interact with the same instance of cal-heatmap.

You `reloadcalendar` function should not re-init the calendar, but just update it, using

`cal.update(url.json)`

All available methods are documented on http://kamisama.github.io/cal-heatmap/#methods

There is no way to auto-detect the limits of your data, as the max of your values is not the 'real' max.
