### ISSUE TITLE
Resizable or scalable calendar

### ISSUE THREAD

**Issue by WinnieK** [kamisama/cal-heatmap#157]
Hello.

Is there any way to make the calendar a bit more responsive on window resize? The problem is that without this feature, it's pretty uncomfortable to use it in liquid full width page layouts. Maybe you can guide me in the right direction? Since it's SVG, probably there is a way to scale cells depending on window size or hide blocks under "next" button, or something like this?

Thanks

**Comment by kamisama** [comment]
Responsive calendar is not supported yet.

See similar issue #100 and #94
