### ISSUE TITLE
Tooltips not aligned correctly when window width > 992px

### ISSUE THREAD

**Issue by diasks2** [kamisama/cal-heatmap#79]
I am using cal-heatmap and bootstrap. When I have tooltips enabled, if the window size expands past 992px the tooltip is not aligned horizontally with the cell. To get around this issue I used the following hack, I'm sure there is a more elegant way to code it though. Thanks again for all your hard work on cal-heatmap, it is awesome!

```
var windowWidth = $(window).width();
if(windowWidth < 768) {
  self.tooltip.attr("style",
   "display: block; " +
   "left: " + (self.positionSubDomainX(d.t) - self.tooltip[0][0].offsetWidth/2 + options.cellSize/2 + parseInt(domainNode.getAttribute("x"), 10)) + "px; " +
   "top: " + (self.positionSubDomainY(d.t) - self.tooltip[0][0].offsetHeight - options.cellSize/2 + parseInt(domainNode.getAttribute("y"), 10)) + "px;")
  ;
}
if(windowWidth > 768 && windowWidth < 992){
  self.tooltip.attr("style",
    "display: block; " +
    "left: " + (self.positionSubDomainX(d.t) - self.tooltip[0][0].offsetWidth/2 + options.cellSize/2 + parseInt(domainNode.getAttribute("x"), 10)) + "px; " +
    "top: " + (self.positionSubDomainY(d.t) - self.tooltip[0][0].offsetHeight - options.cellSize/2 + parseInt(domainNode.getAttribute("y"), 10)) + "px;")
  ;
} 
if(windowWidth > 992 && windowWidth < 1200){
  self.tooltip.attr("style",
    "display: block; " +
    "left: " + (self.positionSubDomainX(d.t) - self.tooltip[0][0].offsetWidth/2 + options.cellSize/2 + parseInt(domainNode.getAttribute("x"), 10) + 67) + "px; " +
    "top: " + (self.positionSubDomainY(d.t) - self.tooltip[0][0].offsetHeight - options.cellSize/2 + parseInt(domainNode.getAttribute("y"), 10)) + "px;")
 ;
}
if(windowWidth > 1200){
  self.tooltip.attr("style",
     "display: block; " +
     "left: " + (self.positionSubDomainX(d.t) - self.tooltip[0][0].offsetWidth/2 + options.cellSize/2 + parseInt(domainNode.getAttribute("x"), 10) + 167) + "px; " +
    "top: " + (self.positionSubDomainY(d.t) - self.tooltip[0][0].offsetHeight - options.cellSize/2 + parseInt(domainNode.getAttribute("y"), 10)) + "px;")
  ;
}
```

**Comment by kamisama** [comment]
Fixed in 3.5.1

**Comment by kunolek** [comment]
I still have problem with bootstrap and tooltips :(

**Comment by kamisama** [comment]
Can you give an excerpt of you html source code ?

**Comment by robert-lewon** [comment]
It was still:

.cal-heatmap-container{
	margin-left: auto;
	margin-right: auto;
}

and <div id="cal-heatmap"></div> is in:

<div class="container">
  <div class="row">
    <div class="col-md-9">
      <div class="row">
        <div class="col-md-12">

**Comment by kamisama** [comment]
Does that works for you ? http://jsfiddle.net/Kamisama/4hxvca5L/

**Comment by robert-lewon** [comment]
No. My intention was to center heatmap in its container. I've done:

#cal-heatmap {
 margin: auto;
}
and centered content of col-md-12 in own way. Now it's ok. I think we shouldn't edit your .cal-heatmap-container and it all be fine. Thanks for great work :)

**Comment by zikis** [comment]
Can you please explain the way to center the heatmap in its container (like col-md-12) and keep the tooptip aligned with it ?

**Comment by kamisama** [comment]
@zikis, did you try my jsfiddle for the tooltip ?

To center, add `margin: 0 auto` to `cal-heatmap-container`.
