### ISSUE TITLE
Cannot pass javascript objects into data

### ISSUE THREAD

**Issue by apontej** [kamisama/cal-heatmap#80]
Hello,

I am trying to pass a Javascript object that I build in my code into the "data" field and it doesn't seem to be working. I've saved the object to a json file and loaded that in and it works perfectly, but I can't get it to do it with a variable.

The cal-heatmap code is: 

```
  var cal = new CalHeatMap();
  cal.init({
    data: datesPlayed,
    dataType: "json",
    start: new Date(2012, 10),
    id: "cal-heatmap",
    domain: "month",
    subDomain: "x_day",
    range: 6
  });
```

And the object is formatted as such:

```
{
  1352437200: 121, 
  1352523600: 52, 
  1352610000: 43, 
  1352696400: 58
  ...
}
```

Is there any way to load the data from a variable?

**Comment by kamisama** [comment]
Closed as invalid. 

I think the code you're using is from the v2 branch, since you're using the `id` option, that was removed in v3. 

Passing data to javascript object does work in the v3 branch.
