### ISSUE TITLE
Day value displaying as -e for all dates

### ISSUE THREAD

**Issue by jordanhammond** [kamisama/cal-heatmap#83]
For some reason all day values are displaying as '-e' for me.
init JS and sample data is below.

![cal-heatmap](https://cloud.githubusercontent.com/assets/3044001/2957985/45130c2c-daa5-11e3-989c-b77a0b1a9ffe.png)

JavaScript
----------------------
	var d = new Date();
	var start = new Date(d.getFullYear()-1, d.getMonth());
	var cal = new CalHeatMap();
	cal.init({
		domain: "month",
		subDomain: "day",
		data: "/admin/event-history",
		domainMargin: [10, 4],
		tooltip: true,
		start: start,
		highlight: "now",
		cellSize: 10,
		range: 13,
		legend: [500, 1500, 3000, 4000, 30000],
		legendMargin: [10],
		legendVerticalPosition: "center",
		legendOrientation: "vertical",
	});

Data
---------------------
    {"1369008000": 351, "1369094400": 371, "1369180800": 697, "1369267200": 494, "1369353600": 482, "1369440000": 1805, "1369526400": 1587, "1369612800": 265, "1369699200": 299, "1369785600": 590, "1369872000": 535, "1369958400": 455, "1370044800": 1509, "1370131200": 1131, "1370217600": 233, "1370304000": 285, "1370390400": 571, "1370476800": 477, "1370563200": 391, "1370649600": 1304, "1370736000": 1025, "1370822400": 249, "1370908800": 312, "1370995200": 456, "1371081600": 485, "1371168000": 317, "1371254400": 1025, "1371340800": 758, "1371427200": 298, "1371513600": 352, "1371600000": 553, "1371686400": 457, "1371772800": 278, "1371859200": 800, "1371945600": 686, "1372032000": 278, "1372118400": 285, "1372204800": 389, "1372291200": 423, "1372377600": 400, "1372464000": 894, "1372550400": 729, "1372636800": 233, "1372723200": 291, "1372809600": 428, "1372896000": 492, "1372982400": 354, "1373068800": 872, "1373155200": 759, "1373241600": 254, "1373328000": 423, "1373414400": 448, "1373500800": 485, "1373587200": 411, "1373673600": 958, "1373760000": 765, "1373846400": 282, "1373932800": 423, "1374019200": 502, "1374105600": 520, "1374192000": 419, "1374278400": 1065, "1374364800": 799, "1374451200": 283, "1374537600": 383, "1374624000": 462, "1374710400": 443, "1374796800": 396, "1374883200": 1166, "1374969600": 925, "1375056000": 264, "1375142400": 374, "1375228800": 444, "1375315200": 427, "1375401600": 444, "1375488000": 1246, "1375574400": 1039, "1375660800": 336, "1375747200": 408, "1375833600": 584, "1375920000": 577, "1376006400": 505, "1376092800": 1640, "1376179200": 1234, "1376265600": 290, "1376352000": 448, "1376438400": 566, "1376524800": 510, "1376611200": 540, "1376697600": 2095, "1376784000": 1429, "1376870400": 304, "1376956800": 512, "1377043200": 657, "1377129600": 528, "1377216000": 589, "1377302400": 2144, "1377388800": 1684, "1377475200": 474, "1377561600": 398, "1377648000": 653, "1377734400": 436, "1377820800": 767, "1377907200": 2386, "1377993600": 2046, "1378080000": 336, "1378166400": 463, "1378252800": 747, "1378339200": 484, "1378425600": 540, "1378512000": 2402, "1378598400": 1964, "1378684800": 342, "1378771200": 450, "1378857600": 728, "1378944000": 478, "1379030400": 676, "1379116800": 3029, "1379203200": 2274, "1379289600": 463, "1379376000": 583, "1379462400": 767, "1379548800": 596, "1379635200": 777, "1379721600": 2949, "1379808000": 2265, "1379894400": 443, "1379980800": 669, "1380067200": 987, "1380153600": 601, "1380240000": 716, "1380326400": 2770, "1380412800": 2485, "1380499200": 373, "1380585600": 463, "1380672000": 707, "1380758400": 492, "1380844800": 751, "1380931200": 3023, "1381017600": 2581, "1381104000": 421, "1381190400": 625, "1381276800": 720, "1381363200": 564, "1381449600": 604, "1381536000": 2655, "1381622400": 2141, "1381708800": 287, "1381795200": 456, "1381881600": 756, "1381968000": 476, "1382054400": 671, "1382140800": 2974, "1382227200": 2525, "1382313600": 327, "1382400000": 561, "1382486400": 825, "1382572800": 585, "1382659200": 744, "1382745600": 2851, "1382832000": 2401, "1382918400": 394, "1383004800": 616, "1383091200": 907, "1383177600": 626, "1383264000": 1185, "1383350400": 2759, "1383436800": 2604, "1383523200": 300, "1383609600": 442, "1383696000": 723, "1383782400": 531, "1383868800": 1378, "1383955200": 2940, "1384041600": 2398, "1384128000": 295, "1384214400": 550, "1384300800": 810, "1384387200": 582, "1384473600": 673, "1384560000": 2554, "1384646400": 2352, "1384732800": 300, "1384819200": 524, "1384905600": 881, "1384992000": 477, "1385078400": 719, "1385164800": 2669, "1385251200": 2211, "1385337600": 305, "1385424000": 558, "1385510400": 744, "1385596800": 558, "1385683200": 805, "1385769600": 2521, "1385856000": 2233, "1385942400": 304, "1386028800": 497, "1386115200": 657, "1386201600": 620, "1386288000": 683, "1386374400": 2284, "1386460800": 1909, "1386547200": 252, "1386633600": 421, "1386720000": 735, "1386806400": 455, "1386892800": 613, "1386979200": 2063, "1387065600": 1883, "1387152000": 276, "1387238400": 357, "1387324800": 565, "1387411200": 390, "1387497600": 579, "1387584000": 1737, "1387670400": 1251, "1387756800": 157, "1387843200": 199, "1387929600": 173, "1388016000": 480, "1388102400": 367, "1388188800": 948, "1388275200": 840, "1388361600": 331, "1388448000": 343, "1388534400": 290, "1388620800": 240, "1388707200": 522, "1388793600": 1272, "1388880000": 1286, "1388966400": 275, "1389052800": 21207, "1389139200": 21518, "1389225600": 672, "1389312000": 686, "1389398400": 1935, "1389484800": 1646, "1389571200": 287, "1389657600": 520, "1389744000": 655, "1389830400": 635, "1389916800": 650, "1390003200": 2091, "1390089600": 1985, "1390176000": 342, "1390262400": 537, "1390348800": 705, "1390435200": 546, "1390521600": 723, "1390608000": 2233, "1390694400": 2051, "1390780800": 350, "1390867200": 513, "1390953600": 731, "1391040000": 691, "1391126400": 735, "1391212800": 2240, "1391299200": 2013, "1391385600": 356, "1391472000": 549, "1391558400": 723, "1391644800": 698, "1391731200": 843, "1391817600": 2373, "1391904000": 2200, "1391990400": 406, "1392076800": 718, "1392163200": 824, "1392249600": 851, "1392336000": 5342, "1392422400": 2539, "1392508800": 2410, "1392595200": 501, "1392681600": 672, "1392768000": 856, "1392854400": 671, "1392940800": 845, "1393027200": 2858, "1393113600": 2346, "1393200000": 438, "1393286400": 664, "1393372800": 843, "1393459200": 743, "1393545600": 875, "1393632000": 2741, "1393718400": 1986, "1393804800": 335, "1393891200": 543, "1393977600": 758, "1394064000": 671, "1394150400": 946, "1394236800": 2879, "1394323200": 2480, "1394409600": 483, "1394496000": 670, "1394582400": 811, "1394668800": 699, "1394755200": 841, "1394841600": 2930, "1394928000": 2718, "1395014400": 391, "1395100800": 549, "1395187200": 730, "1395273600": 574, "1395360000": 774, "1395446400": 3078, "1395532800": 2559, "1395619200": 374, "1395705600": 645, "1395792000": 895, "1395878400": 487, "1395964800": 748, "1396051200": 2969, "1396137600": 2421, "1396224000": 352, "1396310400": 551, "1396396800": 720, "1396483200": 455, "1396569600": 770, "1396656000": 3036, "1396742400": 2582, "1396828800": 487, "1396915200": 538, "1397001600": 834, "1397088000": 505, "1397174400": 789, "1397260800": 3305, "1397347200": 2535, "1397433600": 362, "1397520000": 662, "1397606400": 932, "1397692800": 914, "1397779200": 815, "1397865600": 2328, "1397952000": 1232, "1398038400": 937, "1398124800": 538, "1398211200": 785, "1398297600": 551, "1398384000": 783, "1398470400": 2943, "1398556800": 2487, "1398643200": 405, "1398729600": 537, "1398816000": 833, "1398902400": 839, "1398988800": 663, "1399075200": 2530, "1399161600": 2524, "1399248000": 365, "1399334400": 469, "1399420800": 777, "1399507200": 398, "1399593600": 592, "1399680000": 2472, "1399766400": 2125, "1399852800": 356, "1399939200": 486, "1400025600": 628, "1400112000": 338, "1400198400": 497, "1400284800": 1880, "1400371200": 1403, "1400457600": 161}

**Comment by kamisama** [comment]
Close as inactive.

Please re-open with more browser data if you encounter that issue. I suspect a browser locale issue.
